#!/usr/bin/env bash

#run terraform , we will have a preconfigured terraform config file, and will run inputs here to create the instances

#here we may also create an ssh key, but we have to be able to create and retrieve from terraform.
#lets create the local public key
cd terraform_workspace

terraform destroy -auto-approve
mkdir -p ~/.ssh/my_keys/

if [ ! -f ~/.ssh/my_keys/id_ed25519.pub ]
then
    ssh-keygen -t ed25519 -f ~/.ssh/my_keys/id_ed25519 -N ""
fi

terraform init -input=true
terraform validate
if [ $? -ne 0 ]; then
    echo "Terraform validation failed"
    exit 1
fi
terraform apply -auto-approve
if [ $? -ne 0 ]; then
    echo "Terraform apply failed"
    exit 1
fi

cd ../
python3 change_dns_record.py




#afterwards, possibly from terraform we need to be able to run the plabook here to all of the