#!/usr/bin/env bash

#run terraform , we will have a preconfigured terraform config file, and will run inputs here to create the instances

#here we may also create an ssh key, but we have to be able to create and retrieve from terraform.
#lets create the local public key



mkdir -p ./keys

if [ ! -f ./keys/id_rsa.pub ] 
then
    ssh-keygen -t rsa -b 4096 -f ./keys/id_rsa -N ""
fi

cd terraform_workspace

terraform init -input=true
terraform validate





#afterwards, possibly from terraform we need to be able to run the plabook here to all of the 