---
# tasks file for nginx
- name: Upgrate and Update all packages
  yum:
    name: '*'
    state: latest



- name: Install epel-release and cron
  yum:
    name:
    - yum-utils
    - cronie
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
