---
# tasks file for nginx
- name: Upgrate and Update all packages
  yum:
    name: '*'
    state: latest


- name: Install epel-release
  yum:
    name: yum-utils
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present
